### PR TITLE
Commute data

### PR DESCRIPTION
**Pull request by dlaffoo1**
I finished up v1 of the commute model and controller.. ready to merge it into development.

### CODE REVIEW

**Review by kevinwmiller — CHANGES_REQUESTED** [review]
let or const should be preferred over var as they create scoped variables. var does not.

The async specifier isn't needed in the get function of the model. CommuteDetailsbyZipCode doesn't return a promise, so you can just delete the async modifier

**Review by dlaffoo1 — COMMENTED** [review]
approve

**Comment by dlaffoo1** [comment]
I made changes you requested and also made a few updates to the commute lookup logic (to allow for a zipCode lookup when the commit data doesn't actually have the zipCode.

This is first time using Git. So not sure about the pull request workflow. So, is there something else i need to do to get my changes merged?  and do i need to open a new pull for the changes I just committed?

**Comment by dlaffoo1** [comment]
Still not sure what to do here. I added the const to the globals. and removed the async.

Just pushed up changes to CommuteData branch to add location and zip code geometry data 

The pull is saying the CI build is failing. Not sure why.

**Comment by dlaffoo1** [comment]
i just merged change to CommuteData branch to move data into arrays exported in .js files instead of .json

can you test and merge in dev?

**Review by kevinwmiller — APPROVED** [review]

**Pull request merged**
